### register

POST localhost:8081/api/v1/register
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "adminsecret"
}


### login admin:

POST localhost:8081/api/v1/login
Content-Type: application/json

{
  "username": "admin@mail.com",
  "password": "adminsecret"
}

> {% client.global.set("auth-token", response.body.accessToken,
    "refresh-token", response.body.refreshToken); %}



### login user:

POST localhost:8081/api/v1/login
Content-Type: application/json

{
  "username": "user@mail.com",
  "password": "adminsecret"
}

> {% client.global.set("auth-token", response.body.accessToken,
        "refresh-token", response.body.refreshToken); %}



### GET users

GET localhost:8081/api/v1/users
Authorization: Bearer {{auth-token}}



### get categories

GET localhost:8081/api/v1/categories



### get categories only admins

GET localhost:8081/api/v1/auth-only-categories
Authorization: Bearer {{auth-token}}



### get producers

GET localhost:8081/api/v1/producers



### add product

POST localhost:8081/api/v1/products
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
  "name": "Rower górski SCOTT",
  "description": "Górski rower SCOTT",
  "image": "ZdjecieSCOTT",
  "price": 128.00,
  "productCategories": [],
  "productProducer": null
}

> {% client.global.set("auth-token", response.body.accessToken); %}



### get products

GET localhost:8081/api/v1/products



### get products by categories by POST method

POST http://localhost:8081/api/v1/products/bycategories
Content-Type: application/json

{
  "categoryIds": [1, 3]
}



### get products by categories by GET method

GET http://localhost:8081/api/v1/products/by-categories?categoryIds=1&categoryIds=2&categoryIds=3



### get products by categories by GET method + name category Param

GET http://localhost:8081/api/v1/products/products-by-param?category=Rowery
