### register

POST localhost:8081/api/v1/register
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "adminsecret"
}


### login ok:

POST localhost:8081/api/v1/login
Content-Type: application/json

{
  "username": "admin@mail.com",
  "password": "adminsecret"
}

> {% client.global.set("auth-token", response.body.accessToken,
    "refresh-token", response.body.refreshToken); %}



### Users

GET localhost:8081/api/v1/users
Authorization: Bearer {{auth-token}}

### get products

GET localhost:8081/api/v1/products

### get categories

GET localhost:8081/api/v1/categories


### get producers

GET localhost:8081/api/v1/producers



### add product

POST localhost:8081/api/v1/products
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
  "name": "Rower górski SCOTT",
  "description": "Górski rower SCOTT",
  "image": "ZdjecieSCOTT",
  "price": 128.00,
  "productCategories": [],
  "productProducer": null
}

> {% client.global.set("auth-token", response.body.accessToken); %}
